export enum UserTypes {
  SUPER_ADMIN = 'super_admin',
  ORG_OWNER = 'organization_owner',
  ORG_ADMIN = 'organization_admin',
  MANAGER = 'manager',
  TEAM_LEAD = 'team_lead',
  STAFF = 'staff',
  AGENT = 'agent',
  ORG_AGENT = 'organization_agent',
  LEAD_CRM = 'lead_crm',
  SALES_SETUP = 'sales_setup',
  USER = 'user',
  ALL = 'all',
}

export enum UserFilters {
  'Assigned to Organization' = 'assigned_organisation',
  'Not Assigned to Organization' = 'not_assigned_organisation',
  'Applied for Any Service' = 'applied_service',
  'Not Applied for Any Service' = 'not_applied_service',
}

export const UserTypesMapping: Record<string, string[]> = {
  [UserTypes.SUPER_ADMIN]: [
    UserTypes.USER,
    UserTypes.SUPER_ADMIN,
    UserTypes.ORG_ADMIN,
    UserTypes.ORG_OWNER,
    UserTypes.MANAGER,
    UserTypes.TEAM_LEAD,
    UserTypes.STAFF,
    UserTypes.AGENT,
    UserTypes.ORG_AGENT,
  ],
  [UserTypes.STAFF]: [UserTypes.USER],
  [UserTypes.TEAM_LEAD]: [UserTypes.TEAM_LEAD, UserTypes.STAFF, UserTypes.USER],
  [UserTypes.MANAGER]: [
    UserTypes.USER,
    UserTypes.MANAGER,
    UserTypes.TEAM_LEAD,
    UserTypes.STAFF,
    UserTypes.AGENT,
    UserTypes.ORG_AGENT,
  ],
  [UserTypes.AGENT]: [UserTypes.USER],
  [UserTypes.ORG_OWNER]: [
    UserTypes.USER,
    UserTypes.ORG_ADMIN,
    UserTypes.ORG_OWNER,
    UserTypes.MANAGER,
    UserTypes.TEAM_LEAD,
    UserTypes.STAFF,
    UserTypes.AGENT,
    UserTypes.ORG_AGENT,
  ],
  [UserTypes.ORG_ADMIN]: [
    UserTypes.USER,
    UserTypes.ORG_ADMIN,
    UserTypes.ORG_OWNER,
    UserTypes.MANAGER,
    UserTypes.TEAM_LEAD,
    UserTypes.STAFF,
    UserTypes.AGENT,
    UserTypes.ORG_AGENT,
  ],
  [UserTypes.ORG_AGENT]: [UserTypes.USER],
  [UserTypes.LEAD_CRM]: [UserTypes.USER],
  [UserTypes.SALES_SETUP]: [UserTypes.USER],
};
